version: 2.1

orbs:
  node: circleci/node@4.7
  # The Node.js orb contains a set of prepackaged CircleCI configuration you can utilize
  # See the orb's test job here: https://circleci.com/developer/orbs/orb/circleci/node#jobs-test

jobs:
  test:
    parameters:
      version:
        type: string
    executor:
      name: node/default
      tag: << parameters.version >>
    steps:
      - checkout
      - node/install-npm
      - node/install-packages
      - run: npm test
      - store_test_results:
          path: test-results

workflows:
  tests:
    jobs:
      - test:
          matrix:
            parameters:
              version: ['15.1', 'lts', '12.21']
          # For more information about matrix testing see the detailed blog post:
          # https://circleci.com/blog/circleci-matrix-jobs/
          # or the configuration reference:
          # https://circleci.com/docs/2.0/configuration-reference/?section=reference#matrix-requires-version-21
